#!/usr/bin/env python
"""Three analyses over the PTB-XL label manifest.

Reads data/ptbxl/manifest.jsonl ONLY (never the raw CSVs) and reports:

  1. Normality under three definitions.
  2. Human-validation coverage, per fold and cross-tabulated with autogenerated
     reports.
  3. The full entries of every all-zero-likelihood record.

Usage:
    python scripts/manifest_stats.py --manifest data/ptbxl/manifest.jsonl
"""

import argparse
import json
import os
from collections import Counter

TOTAL = 21799  # stated PTB-XL record count, used for the requested percentages


def load(path):
    records = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                records.append(json.loads(line))
    return records


def codes_of(rec):
    return {s["code"] for s in rec["statements"]}


def diagnostic_codes(rec, nonzero_only=False):
    out = set()
    for s in rec["statements"]:
        if not s["diagnostic"]:
            continue
        if nonzero_only and s["likelihood"] == 0.0:
            continue
        out.add(s["code"])
    return out


def rhythm_form_codes(rec):
    return sorted(s["code"] for s in rec["statements"] if s["rhythm"] or s["form"])


def pct(n, d=TOTAL):
    return f"{100.0 * n / d:.2f}%"


# --------------------------------------------------------------------------- #
# 1. Normality, three definitions
# --------------------------------------------------------------------------- #
def analysis_normality(records, descriptions):
    print("=" * 70)
    print("1. NORMALITY, THREE DEFINITIONS")
    print("=" * 70)

    a = [r for r in records if codes_of(r) == {"NORM"}]
    b = [r for r in records if diagnostic_codes(r) == {"NORM"}]
    c = [r for r in records if diagnostic_codes(r, nonzero_only=True) == {"NORM"}]

    print(f"(a) statement code set exactly {{NORM}}          : {len(a)}  ({pct(len(a))})")
    print(f"(b) diagnostic codes exactly {{NORM}}            : {len(b)}  ({pct(len(b))})")
    print(f"      (rhythm/form codes ignored; likelihood-0 diagnostics still count)")
    print(f"(c) as (b) but likelihood-0 codes ignored too   : {len(c)}  ({pct(len(c))})")
    print()

    print(f"(b) as a percentage of {TOTAL}: {pct(len(b))}")
    print()

    print("Ten most common rhythm/form code sets riding along with NORM under (b):")
    accompanying = Counter(tuple(rhythm_form_codes(r)) for r in b)
    for code_set, count in accompanying.most_common(10):
        if code_set:
            rendered = ", ".join(f"{c} ({descriptions[c]})" for c in code_set)
        else:
            rendered = "(none)"
        print(f"  {count:6d}  {{{rendered}}}")
    print()


# --------------------------------------------------------------------------- #
# 2. Human validation
# --------------------------------------------------------------------------- #
def analysis_validation(records):
    print("=" * 70)
    print("2. HUMAN VALIDATION")
    print("=" * 70)

    n = len(records)
    validated = [r for r in records if r["validated_by_human"]]
    autogen = [r for r in records if r["initial_autogenerated_report"]]

    print(f"validated_by_human == True          : {len(validated)}  ({pct(len(validated), n)})")
    print(f"initial_autogenerated_report == True: {len(autogen)}  ({pct(len(autogen), n)})")
    print(f"(percentages of the {n} manifest records)")
    print()

    print("Breakdown by strat_fold:")
    print(f"  {'fold':>4}  {'records':>8}  {'validated':>10}  {'pct':>7}")
    for fold in range(1, 11):
        in_fold = [r for r in records if r["strat_fold"] == fold]
        val = sum(1 for r in in_fold if r["validated_by_human"])
        p = f"{100.0 * val / len(in_fold):.2f}%" if in_fold else "n/a"
        print(f"  {fold:>4}  {len(in_fold):>8}  {val:>10}  {p:>7}")
    print()

    print("Cross-tabulation (validated_by_human x initial_autogenerated_report):")
    a = sum(1 for r in records if r["validated_by_human"] and r["initial_autogenerated_report"])
    b = sum(1 for r in records if r["validated_by_human"] and not r["initial_autogenerated_report"])
    c = sum(1 for r in records if not r["validated_by_human"] and r["initial_autogenerated_report"])
    d = sum(1 for r in records if not r["validated_by_human"] and not r["initial_autogenerated_report"])
    print(f"  {'':>18}  {'autogen=True':>13}  {'autogen=False':>14}")
    print(f"  {'validated=True':>18}  {a:>13}  {b:>14}")
    print(f"  {'validated=False':>18}  {c:>13}  {d:>14}")
    print(f"  (total: {a + b + c + d})")
    print()


# --------------------------------------------------------------------------- #
# 3. All-zero-likelihood records
# --------------------------------------------------------------------------- #
def _class_flags(s):
    flags = [name for name in ("diagnostic", "form", "rhythm") if s[name]]
    return ",".join(flags) if flags else "(none)"


def analysis_all_zero(records):
    print("=" * 70)
    print("3. ALL-ZERO-LIKELIHOOD RECORDS")
    print("=" * 70)

    all_zero = [
        r
        for r in records
        if r["statements"] and all(s["likelihood"] == 0.0 for s in r["statements"])
    ]
    print(f"records where every statement has likelihood == 0: {len(all_zero)}")
    print()

    for r in all_zero:
        print(f"ecg_id {r['ecg_id']}")
        print(f"  strat_fold          : {r['strat_fold']}")
        print(f"  validated_by_human  : {r['validated_by_human']}")
        print(f"  has any statements  : {bool(r['statements'])} ({len(r['statements'])} codes)")
        print(f"  statements:")
        for s in r["statements"]:
            print(
                f"    {s['code']:8s} likelihood={s['likelihood']:<5} "
                f"class=[{_class_flags(s)}]  {s['description']}"
            )
        print()


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    default = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "data/ptbxl/manifest.jsonl",
    )
    ap.add_argument("--manifest", default=default, help="path to manifest.jsonl")
    args = ap.parse_args()

    records = load(args.manifest)
    descriptions = {s["code"]: s["description"] for r in records for s in r["statements"]}

    print(f"loaded {len(records)} records from {args.manifest}\n")
    analysis_normality(records, descriptions)
    analysis_validation(records)
    analysis_all_zero(records)


if __name__ == "__main__":
    main()
