#!/usr/bin/env python
"""Inspect the free-text `report` field across the manifest working set.

Reads data/ptbxl/manifest.jsonl ONLY. Prints 20 records stratified across five
views, each shown with its SCP statements (description + likelihood) so the
report and the coded labels can be compared side by side. Then reports coverage
stats: empty/missing reports, median report length, and a heuristic count of
non-German reports.

Usage:
    python scripts/report_inspect.py --manifest data/ptbxl/manifest.jsonl
"""

import argparse
import json
import os
import random
import statistics
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))

from src import manifest as M

PER_STRATUM = 4  # 5 strata x 4 = 20 records

# --- language heuristic (no langdetect installed; short telegraphic text) ----
# PTB-XL reports are mostly German but include a clear block of English reports.
# We score unambiguous German vs English anchors -- deliberately avoiding shared
# Latin terms (sinus, infarct, myocardial, anterior, normal...) which appear in
# both -- and treat the ekg/ecg spelling as a strong discriminator. Umlauts imply
# German outright. Printed as a heuristic, not a claim.
GERMAN_UMLAUTS = set("äöüßÄÖÜ")
GERMAN_TOKENS = {
    "sinusrhythmus", "sinusbradykardie", "sinustachykardie", "ekg", "lagetyp",
    "linkstyp", "rechtstyp", "steiltyp", "sonst", "und", "mit", "ohne", "kein",
    "keine", "nicht", "verdacht", "auf", "wahrscheinlich", "niederspannung",
    "unbestätigter", "unbestaetigter", "bericht", "abnorm", "alter", "unbest",
    "ueberdrehter", "überdrehter", "amplitudenkriterien", "linkshypertrophie",
    "extrasystole", "extrasystolen", "vorhofflimmern", "vorhofflattern",
    "linksschenkelblock", "rechtsschenkelblock", "myokardschaden", "normales",
    "mässige", "mäßige", "ableitungen", "verschoben", "hebung", "unauffällig",
}
ENGLISH_TOKENS = {
    "the", "and", "with", "without", "are", "is", "this", "of", "to", "no",
    "due", "may", "be", "there", "otherwise", "consistent", "suggests",
    "possible", "probably", "waves", "wave", "segment", "segments", "seen",
    "best", "evident", "changes", "definite", "pathology", "ecg", "helpful",
    "apparently", "failure", "commonly", "disease", "deviation", "elevated",
    "depressed", "inverted", "slightly", "flat", "low", "strain", "drug",
}
# A few unambiguous Swedish anchors -- PTB-XL contains some Swedish reports whose
# ä/ö would otherwise be read as German. This only catches obvious cases.
SWEDISH_TOKENS = {
    "sinusrytm", "avvikande", "bör", "övervägas", "förlopp", "vänster",
    "höger", "förändringar", "ospecifika",
}


def report_text(rec):
    r = rec.get("report")
    return r if isinstance(r, str) else ""


def is_empty_report(rec):
    return report_text(rec).strip() == ""


def likely_non_german(rec):
    """Heuristic: clear English (or obvious Swedish) signal. Best-effort only.

    Reliable for the English block; catches only obvious Swedish; other
    non-German languages with ä/ö are conservatively read as German.
    """
    txt = report_text(rec).lower()
    if txt.strip() == "":
        return False
    tokens = set(txt.replace(",", " ").replace(".", " ").split())
    if tokens & SWEDISH_TOKENS:
        return True
    if any(c in GERMAN_UMLAUTS for c in txt):
        return False
    de = len(tokens & GERMAN_TOKENS)
    en = len(tokens & ENGLISH_TOKENS)
    return en > 0 and en > de


# --- stratum predicates ------------------------------------------------------
def codes_of(rec):
    return {s["code"] for s in rec["statements"]}


def n_diagnostic(rec):
    return sum(1 for s in rec["statements"] if s["diagnostic"])


def has_signal_quality(rec):
    return any(
        (rec.get(f) or "").strip() != "" for f in M.SIGNAL_QUALITY_FIELDS
    )


STRATA = {
    "NORM+SR only": lambda r: codes_of(r) == {"NORM", "SR"},
    "multi-label abnormal": lambda r: "NORM" not in codes_of(r) and n_diagnostic(r) >= 2,
    "validated_by_human=True": lambda r: r["validated_by_human"],
    "validated_by_human=False": lambda r: not r["validated_by_human"],
    "signal-quality annotated": has_signal_quality,
}


def class_flags(s):
    flags = [name for name in ("diagnostic", "form", "rhythm") if s[name]]
    return ",".join(flags) if flags else "-"


def print_record(rec):
    quality = {
        f: rec.get(f) for f in M.SIGNAL_QUALITY_FIELDS if (rec.get(f) or "").strip()
    }
    txt = report_text(rec)
    print(f"  ecg_id {rec['ecg_id']}  | fold {rec['strat_fold']} "
          f"| validated={rec['validated_by_human']} "
          f"| autogen={rec['initial_autogenerated_report']}")
    if quality:
        print(f"    signal-quality: {quality}")
    print(f"    report ({len(txt)} chars): {txt!r}")
    print(f"    statements:")
    for s in rec["statements"]:
        print(f"      {s['code']:8s} lik={s['likelihood']:<5} [{class_flags(s)}]  {s['description']}")
    print()


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--manifest", default="data/ptbxl/manifest.jsonl")
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()

    records = list(M.load_manifest(args.manifest).values())  # working set (exclusions on)
    rng = random.Random(args.seed)

    print(f"working set: {len(records)} records\n")

    print("=" * 74)
    print("20 RECORDS STRATIFIED ACROSS FIVE VIEWS")
    print("=" * 74)
    for name, pred in STRATA.items():
        pool = [r for r in records if pred(r)]
        sample = rng.sample(pool, min(PER_STRATUM, len(pool)))
        print(f"\n--- {name}  (pool: {len(pool)} records, showing {len(sample)}) ---\n")
        for rec in sample:
            print_record(rec)

    # --- coverage stats ------------------------------------------------------
    print("=" * 74)
    print("REPORT COVERAGE STATS (working set)")
    print("=" * 74)

    empty = sum(1 for r in records if is_empty_report(r))
    print(f"empty or missing report: {empty}  ({100.0 * empty / len(records):.2f}%)")

    lengths_all = [len(report_text(r)) for r in records]
    lengths_nonempty = [n for n in lengths_all if n > 0]
    print(f"median report length (all records)     : {statistics.median(lengths_all)} chars")
    print(f"median report length (non-empty only)  : "
          f"{statistics.median(lengths_nonempty) if lengths_nonempty else 'n/a'} chars")
    print(f"  min/max non-empty length: "
          f"{min(lengths_nonempty)}/{max(lengths_nonempty)} chars")

    non_de = [r for r in records if likely_non_german(r)]
    print(f"likely non-German reports (heuristic)  : {len(non_de)}  "
          f"({100.0 * len(non_de) / len(records):.2f}%)")
    for r in non_de[:10]:
        print(f"    ecg_id {r['ecg_id']}: {report_text(r)!r}")
    print("  (heuristic: flagged on a clear English signal with no German signal; "
          "no langdetect available)")


if __name__ == "__main__":
    main()
