"""Clean the PTB-XL free-text report before the teacher sees it.

Pure functions, no I/O. Two kinds of non-evidence must not reach the teacher:

1. **Autogenerated-report boilerplate.** Unvalidated device output ends with a
   numeric code and the marker ``unbestÄtigter bericht`` ("unconfirmed report").
   It reports annotation quality, not ECG content, so it is stripped along with
   the numeric code that precedes it.
2. **Curator edits.** Some reports have the coded annotation injected back into the
   free text: an ``Edit:`` segment (e.g. ``Edit: NORM 80, ...``) and/or a
   parenthesised label-with-likelihood such as ``(NORM 100, IVCB)``. That leaks the
   label into the evidence channel, so both are stripped.

After stripping, a minimum length floor decides whether any usable free text
survives. Below the floor the record has no usable report and downstream falls
back to annotations-only evidence.

The returned :class:`CleanedReport` carries the cleaned text, a boolean saying
whether a usable report survived, and a :class:`ReportFlags` recording exactly
what was removed -- so a preview or a test can see why a report was gutted.
"""

import re
from dataclasses import asdict, dataclass
from typing import Any, Dict

# Reports run from 1 to 397 chars; below this there is no usable free-text content.
DEFAULT_MIN_REPORT_CHARS = 15

# "<numeric code> ... unbestÄtigter bericht": the autogen boilerplate marker and
# the numeric code that precedes it (e.g. "4.46                  unbestÄtigter
# bericht"). The numeric code is optional so the marker is stripped even when it
# stands alone. ``\w`` matches the umlaut inside "unbest(ä|Ä)tigter", so both the
# Ä and ä spellings are caught -- while the abbreviation "unbest." in "alter
# unbest." ("age indeterminate") is NOT, because it lacks "tigter bericht".
_BOILERPLATE_RE = re.compile(
    r"\s*(?:\d+(?:[.,]\d+)?\s+)?unbest\w*tigter\s+bericht",
    re.IGNORECASE,
)

# A curator's ``Edit:`` segment. The edit is appended to the report, so it runs to
# the end of the string.
_EDIT_RE = re.compile(r"\s*\bEdit:.*$", re.IGNORECASE | re.DOTALL)

# A parenthesised label-with-likelihood such as "(NORM 100, IVCB)", "(CRBBB)" or
# "(LVH 100)". The discriminator is a run of two or more consecutive ASCII
# uppercase letters -- an SCP code. The reports are otherwise lowercase German
# telegraphese, so legitimate parentheticals like "qrs(t)", "(s)", "(er)" or
# "(hebung)" carry no such run and are kept. Embedded uppercase umlauts (Ä, Ö in
# "mÖglich", "ischÄmie") are outside [A-Z] and never trigger a match.
_PAREN_LABEL_RE = re.compile(r"\s*\([^)]*[A-Z]{2,}[^)]*\)")

_WHITESPACE_RE = re.compile(r"\s+")


@dataclass(frozen=True)
class ReportFlags:
    """What report cleaning removed, and whether the length floor was hit."""

    stripped_boilerplate: bool = False
    stripped_edit: bool = False
    stripped_paren_labels: bool = False
    floor_hit: bool = False

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True)
class CleanedReport:
    """Result of :func:`clean_report`.

    ``text`` is the cleaned free text, empty when nothing usable survived.
    ``has_usable_report`` is ``False`` exactly when the record must fall back to
    annotations-only evidence.
    """

    text: str
    has_usable_report: bool
    flags: ReportFlags

    def to_dict(self) -> Dict[str, Any]:
        return {
            "text": self.text,
            "has_usable_report": self.has_usable_report,
            "flags": self.flags.to_dict(),
        }


def _normalise_whitespace(text: str) -> str:
    """Collapse runs of whitespace (PTB-XL pads clauses with many spaces) to one."""
    return _WHITESPACE_RE.sub(" ", text).strip()


def clean_report(
    report: Any, min_chars: int = DEFAULT_MIN_REPORT_CHARS
) -> CleanedReport:
    """Clean a raw report string into evidence-safe free text.

    ``report`` may be ``None`` or a non-string (treated as empty). Stripping order
    is boilerplate, then parenthesised labels, then the ``Edit:`` segment, so a
    record like ``ecg_id`` 18822 -- whose edit contains both a bare label and a
    parenthesised one -- registers every flag it triggers.
    """
    text = report if isinstance(report, str) else ""

    text, n_boilerplate = _BOILERPLATE_RE.subn("", text)
    text, n_paren = _PAREN_LABEL_RE.subn("", text)
    text, n_edit = _EDIT_RE.subn("", text)

    text = _normalise_whitespace(text)
    floor_hit = len(text) < min_chars

    flags = ReportFlags(
        stripped_boilerplate=bool(n_boilerplate),
        stripped_edit=bool(n_edit),
        stripped_paren_labels=bool(n_paren),
        floor_hit=floor_hit,
    )
    return CleanedReport(
        text="" if floor_hit else text,
        has_usable_report=not floor_hit,
        flags=flags,
    )
